name: Trivy Scan

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Verify image pull
        run: docker pull saikumar3093/python-test:v1
      - name: Run Trivy scan on Docker Hub image
        uses: aquasecurity/trivy-action@0.21.0
        with:
          image-ref: saikumar3093/test-python:v2
          format: 'table'
          severity: 'CRITICAL,HIGH'
